[workspace]
authors = ["Sriman Achanta <68172138+srimanachanta@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "nibs_comp"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
pyvista = ">=0.47.1,<0.48"
rich = ">=14.3.3,<15"
meshio = ">=5.3.5,<6"
pymeshfix = ">=0.18.0,<0.19"
